# Generated by Django 4.2 on 2024-11-18 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0001_initial'),
        ('marcas', '0001_initial'),
        ('tipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('codigoColor', models.CharField(max_length=100, verbose_name='CodigoColor')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacenes.almacen', verbose_name='Almacen')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcas.marca', verbose_name='Marca')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipos.tipo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'permissions': [('puede_aprobar', 'Puede aprobar registros'), ('puede_rechazar', 'Puede rechazar registros')],
            },
        ),
    ]
