# Generated by Django 4.2.16 on 2024-10-14 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0001_initial'),
        ('catalogos', '0001_initial'),
        ('marcas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('codigoColor', models.CharField(max_length=100, verbose_name='CodigoColor')),
                ('descripcion', models.CharField(editable=False, max_length=100, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacenes.almacen', verbose_name='Almacen')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.catalogo', verbose_name='Catalogo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marcas.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
